spring:
    datasource:
      driverClassName: org.postgresql.Driver
      platform: postgres
      url: jdbc:postgresql://localhost:5432/senchacrm
      username: kawanoshinobu
      password: 
    jpa:
      show-sql: true
      database: POSTGRESQL
      hibernate:
        ddl-auto: create-drop
